export enum STEP {
    TIME_SLOTS_STEP = 'TIME_SLOTS_STEP',
    CONTACTS_STEP = 'CONTACTS_STEP',
    ADDITIONAL_STEP = 'ADDITIONAL_STEP',
    REVIEW_STEP = 'REVIEW_STEP',
}

export enum STEP_NUMBER {
    TIME_SLOTS_STEP = 0,
    CONTACTS_STEP = 1,
    ADDITIONAL_STEP = 2,
    REVIEW_STEP = 3,
}

export enum STEP_TYPE {
    DATE_INFO = 'DATE_INFO',
    USER_INFO = 'USER_INFO',
    ADDITIONS = 'ADDITIONS',
}

export enum MODE {
    DEFAULT = 'DEFAULT',
    EDIT = 'EDIT',
}
